services:
  persistence:
    build: 
      context: .
      dockerfile: ./persistence/Dockerfile
    container_name: persistence
    volumes:
      - ./storage:/app/storage
    command: ["tail", "-f", "/dev/null"]

  extractor:
    build: 
      context: .
      dockerfile: ./extractor/Dockerfile
    container_name: extractor
    volumes:
      - ./storage:/app/storage
    ports:
      - "5900:5900"

    depends_on:
      - persistence

    # command: ["tail", "-f", "/dev/null"]


  transformer:
    build: 
      context: .
      dockerfile: ./transformer/Dockerfile
    container_name: transformer
    volumes:        
      - ./storage:/app/storage
      # - ./:/app
    depends_on:
      - persistence

    # command: ["tail", "-f", "/dev/null"]
