name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  GitHub-Actions-Start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  TestJob-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1
        run: echo "Hmm... This job is a echo test."
      - name: Echo 2
        run: echo "Hmm... This job is another echo test." | ls -al
      - name: Echo 3
        run: echo "Hmm... This job is yet another echo test." | pwd
      - name: Echo 4
        run: echo "Hmm... This job is still another echo test." | date
        
        